name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable

jobs:
  promote:
    name: Promote
    uses: canonical/observability/.github/workflows/charm-promote.yaml@425ab6a9edd4fbc45ff296107d781ace97b52bf9 # v1
    with:
      promotion: ${{ github.event.inputs.promotion }}
    secrets: inherit
