name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable

jobs:
  promote:
    name: Promote
    uses: canonical/observability/.github/workflows/charm-promote.yaml@051f2b1175c774c86c6ef1f26328982e196dd3ae # v1
    with:
      promotion: ${{ github.event.inputs.promotion }}
    secrets: inherit
