name: Pull Requests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@74295934ced2f43396ea6573274504d04d4cc635 # v1
    secrets: inherit