name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@d5dd87e269baf7e7a3a8c44e7d1441945cab1bfd # v1
    secrets: inherit
