name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@4f7694f975b4757d1d09d9c953a12a07fe499a5f # v1
    secrets: inherit
