name: Pull Requests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@e045e1f7012615d9f9bfe0cdbef12ff19c99a114 # v0
    secrets: inherit