name: Quality Gates

on:
  # Manual trigger
  workflow_dispatch:
  # Run the quality checks periodically
  # FIXME: adjust the frequency as needed once we have actual gates in place
  # schedule:
  #   - cron: "0 0 * * Tue"


jobs:
  quality-gates:
    name: Run quality gates
    uses: canonical/observability/.github/workflows/charm-quality-gates.yaml@636230eacd68c9cb99a2e926126e2bf71a2f87c0 # v1
    secrets: inherit
