name: Quality Gates

on:
  # Manual trigger
  workflow_dispatch:
  # Run the quality checks periodically
  # FIXME: adjust the frequency as needed once we have actual gates in place
  # schedule:
  #   - cron: "0 0 * * Tue"


jobs:
  quality-gates:
    name: Run quality gates
    uses: canonical/observability/.github/workflows/charm-quality-gates.yaml@4f7694f975b4757d1d09d9c953a12a07fe499a5f # v1
    secrets: inherit
