name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@74295934ced2f43396ea6573274504d04d4cc635 # v1
    secrets: inherit