name: Release Charm

on:
  push:
    branches:
      - main
      - track/**
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@fb34efa1a25af16576ee3a5d5d2bc5c748370455 # v1
    secrets: inherit
    with:
      default-track: 2
