name: Release Charm

on:
  push:
    branches:
      - main
      - track/**
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@78f655bd7446ee040b26cfe5d2e095b6dfdc3423 # v1
    secrets: inherit
    with:
      default-track: dev
