name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@924ff36dead22099976a156750e47c07b6bf5134 # v0
    secrets: inherit