name: Release to latest/edge

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "tox.ini"

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      CHARMHUB_TOKEN: "${{ secrets.CHARMHUB_TOKEN }}"

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@65ee829ea0383ce462c2d966986a1f5f17661965 # 2.2.4
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@65ee829ea0383ce462c2d966986a1f5f17661965 # 2.2.4
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
