name: Release Charm

on:
  push:
    branches:
      - main
      - track/**
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@6911b97deaa06e45aa5ce30cd1d6c3f43e0c2283 # v1
    secrets: inherit
    with:
      default-track: 2
