# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@180db1547505e30c02d41959fe65ada1523ee207 # v40.3.0
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
