# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@1c7ebbc0d4d5ce0fbbc0b95f9c01a1c70cdd907f # v34.48.4
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
