# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@d752b2b6fe37f7b544e5a96405f7fe681327a7c3 # v39.0.4
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
