name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday

jobs:
    tics:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@615489cd6e9c46bec525afb49cf3e855c52e8530 # v1
        secrets: inherit
