name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-lib:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@0a7f69ad160488269eed417f1c17c06f6cacc9eb # v1
    secrets: inherit
